= Disconnected support for KMM

*Goal*: describe the requirements and implementation ideas for KMM disconnected support

== Introduction: disconnected in OCP

The term "disconnected clusters" refers to clusters that do not have Internet access and thus cannot download publicly
available container images.
To support disconnected clusters, a private registry must be used.
The registry is installed and managed by the cluster administrator.

Red Hat offers https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-installation-images.html#installing-mirroring-installation-images[documentation]
to mirror the OpenShift system iamges on a private registry.
Under the hood, the tools used:

* copy the container images from the public registry on the Internet to the private one;
* create https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects that configure the mirroring on nodes.
https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects configure alternate locations for images specified *by digest only*.

KMM itself can be mirrored like any operator with the usual tools. +
However, some use cases require the controllers and other components to pull and push images from and to registries.
The operator does not inherit the mirroring configuration of the container runtime on the node, so by default it will
not pull images from mirrored registries.
In those cases, support for mirrored registries as configured in https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects must be
implemented in the operator code.

== In KMM

The scenarios where the operator or one of its components might need to build an image are listed below:

[cols=",^,^"]
|===
| Scenario | Handled by OCP | Work needed

| When the `Module` reconciler checks if the output image already exists
| ❌
| ❌^1^

| When the `PreflightValidation` reconciler checks if the output image already exists
| ❌
| ❌^1^

| When pulling the base image (`FROM` in the `Dockerfile`)
| ✅^2^
| ❌

| When pulling the unsigned image
| ❌
| ✅^3^
|===

*Notes:*

. when build or sign instructions are present, `containerImage` may not refer to an image name by its digest, as it
depends on the output image and is unpredictable.
https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects do not apply here, so we do not need to honor them.
. OpenShift builds honor https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects.
. This only applies to cases where we are only signing and not building.
If we are doing both, then the build output used as the input for the signing job is temporarily stored on the final
registry used for the `containerImage` under a temporary tag; https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects do not apply then.

== In KMM-Hub

KMM-Hub uses the main KMM code to build and sign images, so it also needs to honor https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects
when pulling the unsigned image in the signing context.

In addition to that requirement, we should consider a scenario where the network environment is different for Hubs and
Spokes.
The Hub may be building, signing and pushing an image into a registry `registry.company.com` for Spokes to consume,
but Spokes may only be  able to reach a mirror of the registry at `registry-mirror.company.com`.

----
┌──────────────────────┐                         ┌─────────────────────────────┐
│                      │     Is mirrored to      │                             │
│ registry.company.com─┼─────────────────────────► registry-mirror.company.com │
│                      │                         │                             │
└─────▲────────────────┘                         └──────────────▲──────────────┘
      │                                                         │
      │                                                         │ Pull from
      │ Pushes built image                                      │
      │                                            ┌────────────┼────────────┐
      │                                            │            │            │
   ┌──┴──┐                                    ┌────┴────┐  ┌────┴────┐  ┌────┴────┐
   │     │                                    │         │  │         │  │         │
   │ Hub │                                    │ Spoke 0 │  │ Spoke 1 │  │ Spoke 2 │
   │     │                                    │         │  │         │  │         │
   └──┬──┘                                    └────▲────┘  └────▲────┘  └────▲────┘
      │                                            │            │            │
      └────────────────────────────────────────────┴────────────┴────────────┘
           Creates Module targeting registry.company.com via ManifestWork
----

In that case, even though https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects may be configured on Spokes to redirect from
`registry.company.com` to `registry-mirror.company.com`, the nodes will still try to pull from `registry.company.com` as
specified in the stripped-down `Module` they received from the Hub, because the image name will end with a tag and not a
digest.

== Work needed

* *KMM* and *KMM-Hub*: If a kernel mapping contains only a `sign` section and the `unsignedImage` ends with a
digest, the operator needs to list all possible mirrors for that image using https://docs.openshift.com/container-platform/4.12/rest_api/operator_apis/imagecontentsourcepolicy-operator-openshift-io-v1alpha1.html[`ImageContentSourcePolicy`] objects
configured in the cluster and provide them as parameters to the signing job.
The signing job needs to try and pull from all image locations provided as input.
* *KMM-Hub*: if an image is built and / or signed in-cluster, the operator needs to find out its digest once built and
use that name as the `containerImage` in the stripped-down `Module` it creates on the Spokes.

// Links
